import { readFileSync, writeFileSync } from "node:fs";

const pkg = JSON.parse(readFileSync("./package.json", "utf-8"));
const versionFile = `// Auto-generated by scripts/generate-version.ts
export const version = "${pkg.version}";
`;

writeFileSync("src/version.ts", versionFile);
console.log("Generated src/version.ts with version:", pkg.version);
