import { readFileSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";

const pkg = JSON.parse(readFileSync("./package.json", "utf-8"));
const versionFile = `// Auto-generated by scripts/generate-version.ts
export const version = "${pkg.version}";
`;

writeFileSync("src/version.ts", versionFile);
console.log("Generated src/version.ts with version:", pkg.version);

try {
	// Stage the generated file so downstream git commits (like bumpp's) include it
	execSync("git add src/version.ts", { stdio: "ignore" });
	console.log("Staged src/version.ts");
} catch (err) {
	console.error("Warning: failed to git add src/version.ts:", err && err.message ? err.message : err);
}
