name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        # Use npm ci for reproducible installs when package-lock.json is present.
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build
        run: npm run build

      - name: Create versioned IIFE bundle and zip
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          cd dist
          cp dom-test.iife.js dom-test-${VERSION}.iife.js
          cp dom-test.iife.js.map dom-test-${VERSION}.iife.js.map
          zip -j dom-test-${VERSION}.iife.zip dom-test-${VERSION}.iife.js dom-test-${VERSION}.iife.js.map

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload IIFE assets to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/dom-test-*.iife.zip
            dist/dom-test-*.iife.js
            dist/dom-test-*.iife.js.map
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
